version: '3'
services:
    database:
        image: mysql:5.7
        command:
            - "--character-set-server=utf8"
            - "--collation-server=utf8_unicode_ci"
        container_name: "${PRODUCTION_NAME}-database"
        restart: always
        volumes:
            - "${LOCAL_DATA_MYSQL}:/var/lib/mysql"
        environment:
            MYSQL_USER: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
            TZ: 'Asia/Tokyo'
        networks:
            app_net:
                ipv4_address: '172.16.0.2'
    wordpress:
        depends_on:
            - database
        image: wordpress:fpm
        container_name: "${PRODUCTION_NAME}-wordpress"
        restart: always
        volumes:
            - "${LOCAL_DIRNAME_PUBLIC}:/var/www/html"
        environment:
            WORDPRESS_DB_HOST: database
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            TZ: 'Asia/Tokyo'
        networks:
            app_net:
                ipv4_address: '172.16.0.3'
    nginx:
        depends_on:
            - wordpress
        image: nginx:latest
        container_name: "${PRODUCTION_NAME}-nginx"
        restart: always
        volumes:
            - "${LOCAL_CONFIG_NGINX}:/etc/nginx/conf.d/default.conf"
            - "${LOCAL_DIRNAME_PUBLIC}:/var/www/html"
            - "${LOCAL_DIRNAME_LOG}:/var/log/nginx"
        environment:
            TZ: 'Asia/Tokyo'
        networks:
            app_net:
                ipv4_address: '172.16.0.4'
    https-portal:
        depends_on:
            - nginx
        image: steveltn/https-portal:latest
        container_name: "${PRODUCTION_NAME}-https-portal"
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - "${LOCAL_CONFIG_SSL}:/var/lib/https-portal"
        environment:
            DOMAINS: "${HOST_DOMAIN} -> http://nginx:80/"
            STAGE: "${PRODUCTION_STAGE}"
            CLIENT_MAX_BODY_SIZE: 64M
            TZ: 'Asia/Tokyo'
        networks:
            app_net:
                ipv4_address: '172.16.0.5'
networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: '172.16.0.0/16'
